server:
  port: 9094

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: '1234'
        platform: postgresql
        url: jdbc:postgresql://localhost/revex_customer
        username: revex1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        properties:
          hibernate:
            jdbc:
              lob.non_contextual_creation: true
        hibernate:
          ddl-auto: none
        show-sql: true

authserver:
  hostname: http://localhost:9093
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
